<?xml version="1.0"?>
<doc>
<assembly>
<name>
RevtiTools_vb
</name>
</assembly>
<members>
<member name="M:rvtTools_ez.GeoHelper.GetBottomFace(Autodesk.Revit.DB.FaceArray)">
	<summary>
 Find the bottom face of a face array.
 </summary>
	<param name="faces">A face array.</param>
	<returns>The bottom face of a face array.</returns>
</member><member name="M:rvtTools_ez.GeoHelper.Distribute(Autodesk.Revit.DB.Mesh,Autodesk.Revit.DB.XYZ@,Autodesk.Revit.DB.XYZ@,Autodesk.Revit.DB.XYZ@)">
	<summary>
 Find out the three points which made of a plane.
 </summary>
	<param name="mesh">A mesh contains many points.</param>
	<param name="startPoint">Create a new instance of ReferencePlane.</param>
	<param name="endPoint">The free end apply to reference plane.</param>
	<param name="thirdPnt">A third point needed to define the reference plane.</param>
</member><member name="M:rvtTools_ez.GeoHelper.GetLength(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ)">
	<summary>
 Calculate the length between two points.
 </summary>
	<param name="startPoint">The start point.</param>
	<param name="endPoint">The end point.</param>
	<returns>The length between two points.</returns>
</member><member name="M:rvtTools_ez.GeoHelper.GetDistance(System.Double,System.Double)">
	<summary>
 The distance between two value in a same axis.
 </summary>
	<param name="start">start value.</param>
	<param name="end">end value.</param>
	<returns>The distance between two value.</returns>
</member><member name="M:rvtTools_ez.GeoHelper.GetVector(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ)">
	<summary>
 Get the vector between two points.
 </summary>
	<param name="startPoint">The start point.</param>
	<param name="endPoint">The end point.</param>
	<returns>The vector between two points.</returns>
</member><member name="M:rvtTools_ez.GeoHelper.IsVerticalFace(Autodesk.Revit.DB.Face)">
	<summary>
 Determines whether a face is vertical.
 </summary>
	<param name="face">The face to be determined.</param>
	<returns>Return true if this face is vertical, or else return false.</returns>
</member><member name="M:rvtTools_ez.GeoHelper.IsVerticalEdge(Autodesk.Revit.DB.Edge)">
	<summary>
 Determines whether a edge is vertical.
 </summary>
	<param name="edge">The edge to be determined.</param>
	<returns>Return true if this edge is vertical, or else return false.</returns>
</member><member name="M:rvtTools_ez.GeoHelper.Equal(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ)">
	<summary>
 Determines whether two vector are equal in x and y axis.
 </summary>
	<param name="vectorA">The vector A.</param>
	<param name="vectorB">The vector B.</param>
	<returns>Return true if two vector are equals, or else return false.</returns>
</member><member name="T:rvtTools_ez.GeoHelper">
	<summary>
 A object to help locating with geometry data.
 </summary>
</member><member name="M:rvtTools_ez.Test_ExamplesCodes.GetGeometry">
	<summary>
 返回Element的几何数据
 </summary>
	<remarks></remarks>
</member><member name="M:rvtTools_ez.Test_ExamplesCodes.FindSupporting">
	<summary> 射线法：找到与梁相交的所有墙对象 </summary>
</member><member name="M:rvtTools_ez.Test_ExamplesCodes.FindIntersectWallsByElement">
	<summary> 找到与某Element的几何实体相交的Elements </summary>
</member><member name="M:rvtTools_ez.Test_ExamplesCodes.FindIntersectWallsByGeometry">
	<summary>ElementIntersectsSolidFilter: 找到与某Solid相交的Elements </summary>
</member><member name="M:rvtTools_ez.Test_ExamplesCodes.ElementParameterFilter_FindOjbectsInSpecificRoom(Autodesk.Revit.UI.ExternalCommandData)">
	<summary>
 ElementParameterFilter 参数过滤器：找到一个房间内的所有对象
 </summary>
	<remarks>提示: 参数过滤条件可能比其他的类型过滤条件要快，但是这要视条件而定。毕竟这是一个慢过，使用时请按照过滤标准的复杂程度而异。</remarks>
</member><member name="M:rvtTools_ez.Test_ExamplesCodes.ElementParameterFilter_FindRooms(Autodesk.Revit.DB.Document)">
	<summary>
 ElementParameterFilter参数过滤器 Creates an ElementParameter filter to find rooms whose area is greater than specified value
 </summary>
	<remarks>提示: 参数过滤条件可能比其他的类型过滤条件要快，但是这要视条件而定。毕竟这是一个慢过，使用时请按照过滤标准的复杂程度而异。</remarks>
</member><member name="T:rvtTools_ez.Test_ExamplesCodes">
	<summary>
 一些效果实现的示例代码
 </summary>
	<remarks></remarks>
</member><member name="M:rvtTools_ez.rvtTools.GetWarningValue(System.String)">
	<summary>
 提取WarningValueUsing.dat中的WarningValue类
 </summary>
	<param name="FullPath">WarningValueUsing.dat的绝对路径</param>
</member><member name="T:rvtTools_ez.rvtTools">
	<summary>
	</summary>
	<remarks></remarks>
</member><member name="M:rvtTools_ez.ExtensionMethods.Element(Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.Document)">
	<summary> 从ElementId返回其所在的Document中的Element对象 </summary>
	<param name="elementId"></param>
	<param name="Doc">此elementId所位于的文档</param>
</member><member name="M:rvtTools_ez.ExtensionMethods.FindFamily(Autodesk.Revit.DB.Document,System.String)">
	<summary> 返回项目文档中指定名称的族Family对象 </summary>
	<param name="FamilyName">在此文档中，所要搜索的族对象的名称</param>
</member><member name="M:rvtTools_ez.ExtensionMethods.Instances(Autodesk.Revit.DB.Family)">
	<summary> 返回项目文档中某族Family的所有实例 </summary>
	<param name="Family"></param>
</member><member name="M:rvtTools_ez.ExtensionMethods.Instances(Autodesk.Revit.DB.FamilySymbol)">
	<summary> 返回项目文档中某族类型FamilySymbol的所有实例 </summary>
	<param name="FamilySymbol"></param>
</member><member name="M:rvtTools_ez.ExtensionMethods.ToString_Matrix(Autodesk.Revit.DB.Transform)">
	<summary> 以矩阵的形式返回变换矩阵，仅作显示之用 </summary>
	<param name="Trans"></param>
</member><member name="M:rvtTools_ez.ExtensionMethods.Foot2mm(System.Double)">
	<summary> 长度单位转换：将英尺转换为毫米 1英尺=304.8mm </summary>
	<param name="value_foot"></param>
	<remarks> 1 foot = 12 inches = 304.8 mm</remarks>
</member><member name="T:rvtTools_ez.ExtensionMethods">
	<summary>
 Revit中对象的扩展方法
 </summary>
	<remarks></remarks>
</member><member name="P:My.Resources.Resources.ResourceManager">
	<summary>
  Returns the cached ResourceManager instance used by this class.
</summary>
</member><member name="P:My.Resources.Resources.Culture">
	<summary>
  Overrides the current thread's CurrentUICulture property for all
  resource lookups using this strongly typed resource class.
</summary>
</member><member name="T:My.Resources.Resources">
	<summary>
  A strongly-typed resource class, for looking up localized strings, etc.
</summary>
</member><member name="M:rvtTools_ez.Test_Addin.ExternalApplication.NewRibbon(Autodesk.Revit.UI.UIControlledApplication)">
	<summary>
 创建一个新的 Ribbon
 </summary>
</member>
</members>
</doc>